namespace CodeVeinOutfitInjector
{
	public enum EyeColorAmber
	{
		palette_eye_amber00,
		palette_eye_amber10,
		palette_eye_amber20,
		palette_eye_amber30,
		palette_eye_amber40,
		palette_eye_amber50,
		palette_eye_amber60,
		palette_eye_amber70,
		palette_eye_amber01,
		palette_eye_amber11,
		palette_eye_amber21,
		palette_eye_amber31,
		palette_eye_amber41,
		palette_eye_amber51,
		palette_eye_amber61,
		palette_eye_amber71,
		palette_eye_amber02,
		palette_eye_amber12,
		palette_eye_amber22,
		palette_eye_amber32,
		palette_eye_amber42,
		palette_eye_amber52,
		palette_eye_amber62,
		palette_eye_amber72,
	}
}
