namespace CodeVeinOutfitInjector
{
	public enum EyeColorGreen
	{
		palette_eye_green00,
		palette_eye_green10,
		palette_eye_green20,
		palette_eye_green30,
		palette_eye_green40,
		palette_eye_green50,
		palette_eye_green60,
		palette_eye_green70,
		palette_eye_green01,
		palette_eye_green11,
		palette_eye_green21,
		palette_eye_green31,
		palette_eye_green41,
		palette_eye_green51,
		palette_eye_green61,
		palette_eye_green71,
		palette_eye_green02,
		palette_eye_green12,
		palette_eye_green22,
		palette_eye_green32,
		palette_eye_green42,
		palette_eye_green52,
		palette_eye_green62,
		palette_eye_green72,
	}
}
