namespace CodeVeinOutfitInjector
{
	public enum HairColorGinger
	{
		palette_hair_ginger00,
		palette_hair_ginger10,
		palette_hair_ginger20,
		palette_hair_ginger30,
		palette_hair_ginger40,
		palette_hair_ginger50,
		palette_hair_ginger60,
		palette_hair_ginger70,
		palette_hair_ginger01,
		palette_hair_ginger11,
		palette_hair_ginger21,
		palette_hair_ginger31,
		palette_hair_ginger41,
		palette_hair_ginger51,
		palette_hair_ginger61,
		palette_hair_ginger71,
		palette_hair_ginger02,
		palette_hair_ginger12,
		palette_hair_ginger22,
		palette_hair_ginger32,
		palette_hair_ginger42,
		palette_hair_ginger52,
		palette_hair_ginger62,
		palette_hair_ginger72,
	}
}
