namespace CodeVeinOutfitInjector
{
	public enum HairColorBlonde
	{
		palette_hair_blonde00,
		palette_hair_blonde10,
		palette_hair_blonde20,
		palette_hair_blonde30,
		palette_hair_blonde40,
		palette_hair_blonde50,
		palette_hair_blonde60,
		palette_hair_blonde70,
		palette_hair_blonde01,
		palette_hair_blonde11,
		palette_hair_blonde21,
		palette_hair_blonde31,
		palette_hair_blonde41,
		palette_hair_blonde51,
		palette_hair_blonde61,
		palette_hair_blonde71,
		palette_hair_blonde02,
		palette_hair_blonde12,
		palette_hair_blonde22,
		palette_hair_blonde32,
		palette_hair_blonde42,
		palette_hair_blonde52,
		palette_hair_blonde62,
		palette_hair_blonde72,
	}
}
