namespace CodeVeinOutfitInjector
{
	public enum InnerColorB
	{
		palette_preset_inner_B00,
		palette_preset_inner_B10,
		palette_preset_inner_B20,
		palette_preset_inner_B30,
		palette_preset_inner_B40,
		palette_preset_inner_B50,
		palette_preset_inner_B60,
		palette_preset_inner_B70,
		palette_preset_inner_B01,
		palette_preset_inner_B11,
		palette_preset_inner_B21,
		palette_preset_inner_B31,
		palette_preset_inner_B41,
		palette_preset_inner_B51,
		palette_preset_inner_B61,
		palette_preset_inner_B71,
		palette_preset_inner_B02,
		palette_preset_inner_B12,
		palette_preset_inner_B22,
		palette_preset_inner_B32,
		palette_preset_inner_B42,
		palette_preset_inner_B52,
		palette_preset_inner_B62,
		palette_preset_inner_B72,
	}
}
