namespace CodeVeinOutfitInjector
{
	public enum InnerColorF
	{
		palette_preset_inner_F00,
		palette_preset_inner_F10,
		palette_preset_inner_F20,
		palette_preset_inner_F30,
		palette_preset_inner_F40,
		palette_preset_inner_F50,
		palette_preset_inner_F60,
		palette_preset_inner_F70,
		palette_preset_inner_F01,
		palette_preset_inner_F11,
		palette_preset_inner_F21,
		palette_preset_inner_F31,
		palette_preset_inner_F41,
		palette_preset_inner_F51,
		palette_preset_inner_F61,
		palette_preset_inner_F71,
		palette_preset_inner_F02,
		palette_preset_inner_F12,
		palette_preset_inner_F22,
		palette_preset_inner_F32,
		palette_preset_inner_F42,
		palette_preset_inner_F52,
		palette_preset_inner_F62,
		palette_preset_inner_F72,
	}
}
