namespace CodeVeinOutfitInjector
{
	public enum InnerColorG
	{
		palette_preset_inner_G00,
		palette_preset_inner_G10,
		palette_preset_inner_G20,
		palette_preset_inner_G30,
		palette_preset_inner_G40,
		palette_preset_inner_G50,
		palette_preset_inner_G60,
		palette_preset_inner_G70,
		palette_preset_inner_G01,
		palette_preset_inner_G11,
		palette_preset_inner_G21,
		palette_preset_inner_G31,
		palette_preset_inner_G41,
		palette_preset_inner_G51,
		palette_preset_inner_G61,
		palette_preset_inner_G71,
		palette_preset_inner_G02,
		palette_preset_inner_G12,
		palette_preset_inner_G22,
		palette_preset_inner_G32,
		palette_preset_inner_G42,
		palette_preset_inner_G52,
		palette_preset_inner_G62,
		palette_preset_inner_G72,
	}
}
