namespace CodeVeinOutfitInjector
{
	public enum PresetColor9
	{
		palette_preset_winnterfall00,
		palette_preset_winnterfall10,
		palette_preset_winnterfall20,
		palette_preset_winnterfall30,
		palette_preset_winnterfall40,
		palette_preset_winnterfall50,
		palette_preset_winnterfall60,
		palette_preset_winnterfall70,
		palette_preset_winnterfall01,
		palette_preset_winnterfall11,
		palette_preset_winnterfall21,
		palette_preset_winnterfall31,
		palette_preset_winnterfall41,
		palette_preset_winnterfall51,
		palette_preset_winnterfall61,
		palette_preset_winnterfall71,
		palette_preset_winnterfall02,
		palette_preset_winnterfall12,
		palette_preset_winnterfall22,
		palette_preset_winnterfall32,
		palette_preset_winnterfall42,
		palette_preset_winnterfall52,
		palette_preset_winnterfall62,
		palette_preset_winnterfall72,
	}
}
