namespace CodeVeinOutfitInjector
{
	public enum PresetColor_Makeup1
	{
		palette_preset_makeup00,
		palette_preset_makeup10,
		palette_preset_makeup20,
		palette_preset_makeup30,
		palette_preset_makeup40,
		palette_preset_makeup50,
		palette_preset_makeup60,
		palette_preset_makeup70,
		palette_preset_makeup01,
		palette_preset_makeup11,
		palette_preset_makeup21,
		palette_preset_makeup31,
		palette_preset_makeup41,
		palette_preset_makeup51,
		palette_preset_makeup61,
		palette_preset_makeup71,
		palette_preset_makeup02,
		palette_preset_makeup12,
		palette_preset_makeup22,
		palette_preset_makeup32,
		palette_preset_makeup42,
		palette_preset_makeup52,
		palette_preset_makeup62,
		palette_preset_makeup72,
	}
}
