namespace CodeVeinOutfitInjector
{
	public enum PresetColor1
	{
		palette_preset_acidrain00,
		palette_preset_acidrain10,
		palette_preset_acidrain20,
		palette_preset_acidrain30,
		palette_preset_acidrain40,
		palette_preset_acidrain50,
		palette_preset_acidrain60,
		palette_preset_acidrain70,
		palette_preset_acidrain01,
		palette_preset_acidrain11,
		palette_preset_acidrain21,
		palette_preset_acidrain31,
		palette_preset_acidrain41,
		palette_preset_acidrain51,
		palette_preset_acidrain61,
		palette_preset_acidrain71,
		palette_preset_acidrain02,
		palette_preset_acidrain12,
		palette_preset_acidrain22,
		palette_preset_acidrain32,
		palette_preset_acidrain42,
		palette_preset_acidrain52,
		palette_preset_acidrain62,
		palette_preset_acidrain72,
	}
}
