namespace CodeVeinOutfitInjector
{
	public enum PresetColor_Makeup2
	{
		palette_preset_makeup200,
		palette_preset_makeup210,
		palette_preset_makeup220,
		palette_preset_makeup230,
		palette_preset_makeup240,
		palette_preset_makeup250,
		palette_preset_makeup260,
		palette_preset_makeup270,
		palette_preset_makeup201,
		palette_preset_makeup211,
		palette_preset_makeup221,
		palette_preset_makeup231,
		palette_preset_makeup241,
		palette_preset_makeup251,
		palette_preset_makeup261,
		palette_preset_makeup271,
		palette_preset_makeup202,
		palette_preset_makeup212,
		palette_preset_makeup222,
		palette_preset_makeup232,
		palette_preset_makeup242,
		palette_preset_makeup252,
		palette_preset_makeup262,
		palette_preset_makeup272,
	}
}
