namespace CodeVeinOutfitInjector
{
	public enum PresetColor4
	{
		palette_preset_earth_fire00,
		palette_preset_earth_fire10,
		palette_preset_earth_fire20,
		palette_preset_earth_fire30,
		palette_preset_earth_fire40,
		palette_preset_earth_fire50,
		palette_preset_earth_fire60,
		palette_preset_earth_fire70,
		palette_preset_earth_fire01,
		palette_preset_earth_fire11,
		palette_preset_earth_fire21,
		palette_preset_earth_fire31,
		palette_preset_earth_fire41,
		palette_preset_earth_fire51,
		palette_preset_earth_fire61,
		palette_preset_earth_fire71,
		palette_preset_earth_fire02,
		palette_preset_earth_fire12,
		palette_preset_earth_fire22,
		palette_preset_earth_fire32,
		palette_preset_earth_fire42,
		palette_preset_earth_fire52,
		palette_preset_earth_fire62,
		palette_preset_earth_fire72,
	}
}
