namespace CodeVeinOutfitInjector
{
	public enum PresetColor_Makeup4
	{
		palette_preset_makeup400,
		palette_preset_makeup410,
		palette_preset_makeup420,
		palette_preset_makeup430,
		palette_preset_makeup440,
		palette_preset_makeup450,
		palette_preset_makeup460,
		palette_preset_makeup470,
		palette_preset_makeup401,
		palette_preset_makeup411,
		palette_preset_makeup421,
		palette_preset_makeup431,
		palette_preset_makeup441,
		palette_preset_makeup451,
		palette_preset_makeup461,
		palette_preset_makeup471,
		palette_preset_makeup402,
		palette_preset_makeup412,
		palette_preset_makeup422,
		palette_preset_makeup432,
		palette_preset_makeup442,
		palette_preset_makeup452,
		palette_preset_makeup462,
		palette_preset_makeup472,
	}
}
