namespace CodeVeinOutfitInjector
{
	public enum SkinColor1
	{
		palette_st_ivorybrown00,
		palette_st_ivorybrown10,
		palette_st_ivorybrown20,
		palette_st_ivorybrown30,
		palette_st_ivorybrown40,
		palette_st_ivorybrown50,
		palette_st_ivorybrown60,
		palette_st_ivorybrown70,
		palette_st_ivorybrown01,
		palette_st_ivorybrown11,
		palette_st_ivorybrown21,
		palette_st_ivorybrown31,
		palette_st_ivorybrown41,
		palette_st_ivorybrown51,
		palette_st_ivorybrown61,
		palette_st_ivorybrown71,
		palette_st_ivorybrown02,
		palette_st_ivorybrown12,
		palette_st_ivorybrown22,
		palette_st_ivorybrown32,
		palette_st_ivorybrown42,
		palette_st_ivorybrown52,
		palette_st_ivorybrown62,
		palette_st_ivorybrown72,
	}
}
