namespace CodeVeinOutfitInjector
{
	public enum SkinColor2
	{
		palette_st_vividbrown00,
		palette_st_vividbrown10,
		palette_st_vividbrown20,
		palette_st_vividbrown30,
		palette_st_vividbrown40,
		palette_st_vividbrown50,
		palette_st_vividbrown60,
		palette_st_vividbrown70,
		palette_st_vividbrown01,
		palette_st_vividbrown11,
		palette_st_vividbrown21,
		palette_st_vividbrown31,
		palette_st_vividbrown41,
		palette_st_vividbrown51,
		palette_st_vividbrown61,
		palette_st_vividbrown71,
		palette_st_vividbrown02,
		palette_st_vividbrown12,
		palette_st_vividbrown22,
		palette_st_vividbrown32,
		palette_st_vividbrown42,
		palette_st_vividbrown52,
		palette_st_vividbrown62,
		palette_st_vividbrown72,
	}
}
