namespace CodeVeinOutfitInjector
{
	public enum SkinColor6
	{
		palette_st_goldbrown00,
		palette_st_goldbrown10,
		palette_st_goldbrown20,
		palette_st_goldbrown30,
		palette_st_goldbrown40,
		palette_st_goldbrown50,
		palette_st_goldbrown60,
		palette_st_goldbrown70,
		palette_st_goldbrown01,
		palette_st_goldbrown11,
		palette_st_goldbrown21,
		palette_st_goldbrown31,
		palette_st_goldbrown41,
		palette_st_goldbrown51,
		palette_st_goldbrown61,
		palette_st_goldbrown71,
		palette_st_goldbrown02,
		palette_st_goldbrown12,
		palette_st_goldbrown22,
		palette_st_goldbrown32,
		palette_st_goldbrown42,
		palette_st_goldbrown52,
		palette_st_goldbrown62,
		palette_st_goldbrown72,
	}
}
