namespace CodeVeinOutfitInjector
{
	public enum StandardColor_Green1
	{
		palette_stg_green00,
		palette_stg_green10,
		palette_stg_green20,
		palette_stg_green30,
		palette_stg_green40,
		palette_stg_green50,
		palette_stg_green60,
		palette_stg_green70,
		palette_stg_green01,
		palette_stg_green11,
		palette_stg_green21,
		palette_stg_green31,
		palette_stg_green41,
		palette_stg_green51,
		palette_stg_green61,
		palette_stg_green71,
		palette_stg_green02,
		palette_stg_green12,
		palette_stg_green22,
		palette_stg_green32,
		palette_stg_green42,
		palette_stg_green52,
		palette_stg_green62,
		palette_stg_green72,
	}
}
