namespace CodeVeinOutfitInjector
{
	public enum StandardColor_Blue2
	{
		palette_stg_blue00,
		palette_stg_blue10,
		palette_stg_blue20,
		palette_stg_blue30,
		palette_stg_blue40,
		palette_stg_blue50,
		palette_stg_blue60,
		palette_stg_blue70,
		palette_stg_blue01,
		palette_stg_blue11,
		palette_stg_blue21,
		palette_stg_blue31,
		palette_stg_blue41,
		palette_stg_blue51,
		palette_stg_blue61,
		palette_stg_blue71,
		palette_stg_blue02,
		palette_stg_blue12,
		palette_stg_blue22,
		palette_stg_blue32,
		palette_stg_blue42,
		palette_stg_blue52,
		palette_stg_blue62,
		palette_stg_blue72,
	}
}
