namespace CodeVeinOutfitInjector
{
	public enum StandardColor_Red4
	{
		palette_stg_trueblood00,
		palette_stg_trueblood10,
		palette_stg_trueblood20,
		palette_stg_trueblood30,
		palette_stg_trueblood40,
		palette_stg_trueblood50,
		palette_stg_trueblood60,
		palette_stg_trueblood70,
		palette_stg_trueblood01,
		palette_stg_trueblood11,
		palette_stg_trueblood21,
		palette_stg_trueblood31,
		palette_stg_trueblood41,
		palette_stg_trueblood51,
		palette_stg_trueblood61,
		palette_stg_trueblood71,
		palette_stg_trueblood02,
		palette_stg_trueblood12,
		palette_stg_trueblood22,
		palette_stg_trueblood32,
		palette_stg_trueblood42,
		palette_stg_trueblood52,
		palette_stg_trueblood62,
		palette_stg_trueblood72,
	}
}
