namespace CodeVeinOutfitInjector
{
	public enum StandardColor_Red3
	{
		palette_stg_redyellow00,
		palette_stg_redyellow10,
		palette_stg_redyellow20,
		palette_stg_redyellow30,
		palette_stg_redyellow40,
		palette_stg_redyellow50,
		palette_stg_redyellow60,
		palette_stg_redyellow70,
		palette_stg_redyellow01,
		palette_stg_redyellow11,
		palette_stg_redyellow21,
		palette_stg_redyellow31,
		palette_stg_redyellow41,
		palette_stg_redyellow51,
		palette_stg_redyellow61,
		palette_stg_redyellow71,
		palette_stg_redyellow02,
		palette_stg_redyellow12,
		palette_stg_redyellow22,
		palette_stg_redyellow32,
		palette_stg_redyellow42,
		palette_stg_redyellow52,
		palette_stg_redyellow62,
		palette_stg_redyellow72,
	}
}
