namespace CodeVeinOutfitInjector
{
	public enum StandardColor_Blue1
	{
		palette_stg_bluegreen00,
		palette_stg_bluegreen10,
		palette_stg_bluegreen20,
		palette_stg_bluegreen30,
		palette_stg_bluegreen40,
		palette_stg_bluegreen50,
		palette_stg_bluegreen60,
		palette_stg_bluegreen70,
		palette_stg_bluegreen01,
		palette_stg_bluegreen11,
		palette_stg_bluegreen21,
		palette_stg_bluegreen31,
		palette_stg_bluegreen41,
		palette_stg_bluegreen51,
		palette_stg_bluegreen61,
		palette_stg_bluegreen71,
		palette_stg_bluegreen02,
		palette_stg_bluegreen12,
		palette_stg_bluegreen22,
		palette_stg_bluegreen32,
		palette_stg_bluegreen42,
		palette_stg_bluegreen52,
		palette_stg_bluegreen62,
		palette_stg_bluegreen72,
	}
}
